Django笔记和代码(5月3日)/chapter05/class_view_demo - 副本/class_view_demo/urls.py
from django.urls import path,include
from . import views
from django.views.generic import TemplateView

urlpatterns = [
    path('', views.index,name='index'),
    path('book/', views.BookListView.as_view(),name='book_list'),
    path('add_book/', views.AddBookView.as_view(),name='add_book'),
    path('detail/<book_id>/',views.BookDetailView.as_view(),name='detail'),
    # 以后如果渲染的这个模板不需要传递任何的参数，那么建议在urls中使用TemplateView
    # path('about/',TemplateView.as_view(template_name='about.html'))
    path('about/',views.AboutView.as_view()),
    path('article/',include('front.urls'))
]

Django笔记和代码(5月3日)/chapter05/class_view_demo - 副本/front/urls.py
#encoding: utf-8
from django.urls import path
from . import views

app_name = 'front'

urlpatterns = [
    path('add/',views.add_article,name='add_article'),
    path('list/',views.ArticleListView.as_view(),name='article_list')
]

Django笔记和代码(5月3日)/chapter05/class_view_demo - 副本/front/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)

Django笔记和代码(5月3日)/chapter05/class_view_demo - 副本/class_view_demo/views.py
#encoding: utf-8
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import View,TemplateView

def index(request):
    return HttpResponse('index')

class BookListView(View):
    def get(self,request,*args,**kwargs):
        return HttpResponse("book list view")

class AddBookView(View):
    def get(self,request,*args,**kwargs):
        return render(request,'add_book.html')

    def post(self,request,*args,**kwargs):
        book_name = request.POST.get("name")
        book_author = request.POST.get("author")
        print("name:{},author:{}".format(book_name,book_author))
        return HttpResponse("success")

class BookDetailView(View):
    def get(self,request,book_id):
        print('图书的id是：%s'%book_id)
        return HttpResponse("success")
    
    def dispatch(self, request, *args, **kwargs):
        print('dispatch')
        return super(BookDetailView, self).dispatch(request,*args,**kwargs)

    def http_method_not_allowed(self, request, *args, **kwargs):
        return HttpResponse("不支持GET以外的其他请求！")

class AboutView(TemplateView):
    template_name = 'about.html'

    def get_context_data(self, **kwargs):
        context = {"phone":'0731-888888'}
        return context

Django笔记和代码(5月3日)/chapter05/class_view_demo - 副本/front/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Article
from django.views.generic import ListView
from django.core.paginator import Paginator,Page

def add_article(request):
    articles = []
    for x in range(0,102):
        article = Article(title='标题：%s'%x,content='内容：%s'%x)
        articles.append(article)
    Article.objects.bulk_create(articles)
    return HttpResponse('article added successfully')

class ArticleListView(ListView):
    model = Article
    template_name = 'article_list.html'
    context_object_name = 'articles'
    paginate_by = 10
    ordering = 'create_time'
    page_kwarg = 'p'

    def get_context_data(self, **kwargs):
        context = super(ArticleListView, self).get_context_data(*kwargs)
        context['username'] = 'zhiliao'
        paginator = context.get('paginator')
        page_obj = context.get('page_obj')
        print(page_obj.number)
        return context

    # def get_queryset(self):
    #     return Article.objects.filter(id__lte=9)

Django笔记和代码(5月3日)/chapter05/class_view_demo - 副本/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    这是关于我们的页面{{ phone }}
</body>
</html>

Django笔记和代码(5月3日)/chapter05/class_view_demo - 副本/templates/add_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="post">
    <table>
        <tbody>
            <tr>
                <td>图书名字：</td>
                <td><input type="text" name="name"></td>
            </tr>
            <tr>
                <td>作者：</td>
                <td><input type="text" name="author"></td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit" value="提交"></td>
            </tr>
        </tbody>
    </table>
</form>
</body>
</html>

Django笔记和代码(5月3日)/chapter05/class_view_demo - 副本/templates/article_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
    <ul>
        {% for article in articles %}
            <li>{{ article.title }}</li>
        {% endfor %}
        <ul class="pagination">
            {# 上一页  #}
            {% if page_obj.has_previous %}
                <li><a href="{% url 'front:article_list' %}?p={{ page_obj.previous_page_number }}">上一页</a></li>
            {% else %}
                <li class="disabled"><a href="javascript:void(0);">上一页</a></li>
            {% endif %}

            {# 中间的页码 #}
            {% for page in paginator.page_range %}
                {% if page == page_obj.number %}
                    <li class="active"><a href="javascript:void(0);">{{ page }}</a></li>
                {% else %}
                    <li><a href="{% url 'front:article_list' %}?p={{ page }}">{{ page }}</a></li>
                {% endif %}
            {% endfor %}

            {# 下一页 #}
            {% if page_obj.has_next %}
                <li><a href="{% url 'front:article_list' %}?p={{ page_obj.next_page_number }}">下一页</a></li>
            {% else %}
                <li class="disabled"><a href="javascript:void(0);">下一页</a></li>
            {% endif %}

        </ul>
    </ul>
</body>
</html>